// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzcIwT502V-SA-F1xeZ6PAqPDdWjyBMIo',
    appId: '1:705122987758:web:a9bc18997c71513fdfcdff',
    messagingSenderId: '705122987758',
    projectId: 'busicount-31c15',
    authDomain: 'busicount-31c15.firebaseapp.com',
    storageBucket: 'busicount-31c15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTafQQg9wBb9RKqyy8HIaCQ_eE5K7_ELA',
    appId: '1:705122987758:android:e3b1784925ee2631dfcdff',
    messagingSenderId: '705122987758',
    projectId: 'busicount-31c15',
    storageBucket: 'busicount-31c15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy6pF3iWRc2R0nRCCdlv7GlMmfUYzAYs4',
    appId: '1:705122987758:ios:1bf19719b8fbe4dfdfcdff',
    messagingSenderId: '705122987758',
    projectId: 'busicount-31c15',
    storageBucket: 'busicount-31c15.appspot.com',
    androidClientId: '705122987758-urbnjkl02gunjn8ofvst5ecnqitboetv.apps.googleusercontent.com',
    iosClientId: '705122987758-7nh9mdvp4k0v2a9575u7veve4mqo97jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.busi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy6pF3iWRc2R0nRCCdlv7GlMmfUYzAYs4',
    appId: '1:705122987758:ios:a3fd79ee2b96979fdfcdff',
    messagingSenderId: '705122987758',
    projectId: 'busicount-31c15',
    storageBucket: 'busicount-31c15.appspot.com',
    androidClientId: '705122987758-urbnjkl02gunjn8ofvst5ecnqitboetv.apps.googleusercontent.com',
    iosClientId: '705122987758-mlh94e1n4ljd2nal8pg957k3tac8jq33.apps.googleusercontent.com',
    iosBundleId: 'com.example.busi.RunnerTests',
  );
}
